# disable rules that conflict with prettier
inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml
# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: true
  Max: 120
  AllowURI: true
  URISchemes:
    - http
    - https
